@startuml AutomatedLinkAcceptanceFlow

skinparam componentStyle rectangle

title
UserDemand - AutomatedLinkAcceptance 2.0
end title

actor USER as USER

package "AutomatedLinkAcceptance 2.0" {
  interface GUI as GUI
  USER -[hidden] GUI
  component [APT\n] as APT
  GUI -[hidden] APT
  component [MO\n1.0.0] as MO
  APT -[hidden] MO
  component [Connection\nPreparation] as ConnectionPreparation
  MO -[hidden] ConnectionPreparation

  component [MM\n1.0.0] as MM
  MO -[hidden]- MM
  component [E_Mediator\nManager] as E_MediatorManager
  MO -[hidden] E_MediatorManager
  component [E_Mediator\nInstance] as E_MediatorInstance
  E_MediatorManager -[hidden]- E_MediatorInstance
  component [TrafficeNode\netc.] as E_Device
  E_MediatorInstance -[hidden] E_Device
  component [H_Mediator\nManager] as H_MediatorManager
  E_MediatorInstance -[hidden]- H_MediatorManager
  component [H_Mediator\nInstance] as H_MediatorInstance
  E_MediatorInstance -[hidden]- H_MediatorInstance
  H_MediatorManager -[hidden]- H_MediatorInstance
  component [RTN900\netc.] as H_Device
  H_MediatorInstance -[hidden] H_Device
  E_Device -[hidden]- H_Device
  component [S_Mediator\nManager] as S_MediatorManager
  H_MediatorInstance -[hidden]- S_MediatorManager
  component [S_Mediator\nInstance] as S_MediatorInstance
  H_MediatorInstance -[hidden]- S_MediatorInstance
  S_MediatorManager -[hidden]- S_MediatorInstance
  component [ALC+2e\netc.] as S_Device 
  S_MediatorInstance -[hidden] S_Device
  H_Device -[hidden]- S_Device

  component [LILW\n1.0.0] as LILW
  component [PM\n1.0.0] as PM
  component [MWDG\n1.1.0] as MWDG

  component [APTP\n1.1.0] as APTP
  component [MWDI\n1.2.0] as MWDI
  component [ODL\n] as ODL

  USER - GUI #LightSalmon
  GUI -> APT #LightSalmon : 1.0

  APT -> MO #SkyBlue : 2.1

  MO -> ConnectionPreparation #SkyBlue : 2.2.1
  ConnectionPreparation ..> E_Device #SkyBlue : 2.2.2e
  ConnectionPreparation ..> H_Device #SkyBlue : 2.2.2h
  ConnectionPreparation ..> S_Device #SkyBlue : 2.2.2s

  MO -> MM #SkyBlue : 2.3.1
  MM -> E_MediatorManager #SkyBlue : 2.3.2e
  E_MediatorManager ..> E_MediatorInstance #SkyBlue : create 2.3.3e
  MM -> H_MediatorManager #SkyBlue : 2.3.2h
  H_MediatorManager ..> H_MediatorInstance #SkyBlue : create 2.3.3h
  MM -> S_MediatorManager #SkyBlue : 2.3.2s
  S_MediatorManager ..> S_MediatorInstance #SkyBlue : create 2.3.3s

  MO -> ODL #SkyBlue : 2.4

  MO -> LILW #SkyBlue : 2.5.1
  LILW -> MWDG #SkyBlue : 2.5.2
  MWDG -> ODL #SkyBlue : 2.5.3

  MO -> PM #SkyBlue : 2.6

  ODL -> E_MediatorInstance #SkyBlue : 2.5.4e
  ODL -> H_MediatorInstance #SkyBlue : 2.5.4h
  ODL -> S_MediatorInstance #SkyBlue : 2.5.4s
  E_MediatorInstance -> E_Device #SkyBlue : 2.5.5e
  H_MediatorInstance -> H_Device #SkyBlue : 2.5.5h
  S_MediatorInstance -> S_Device #SkyBlue : 2.5.5s


  APT --> APTP #LightSalmon : 3.1
  APTP -> MWDI #LightSalmon : 3.2
  MWDI -> ODL #LightSalmon : 3.3
  ODL -> E_MediatorInstance #LightSalmon : 3.4e
  ODL -> H_MediatorInstance #LightSalmon : 3.4h
  ODL -> S_MediatorInstance #LightSalmon : 3.4s
  E_MediatorInstance -> E_Device #LightSalmon : 3.5e
  H_MediatorInstance -> H_Device #LightSalmon : 3.5h
  S_MediatorInstance -> S_Device #LightSalmon : 3.5s

}

@enduml